# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

analyzer:
  errors:
    lines_longer_than_80_chars: ignore
  exclude:
    - lib/firebase_options.dart
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
